name: Install dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.18
        cache: 'npm'

    - name: Cache node_modules
      id: modules-cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

    - name: Install node_modules
      if: steps.modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
